@echo off
echo Cleaning previous installations ...
rd /s /q build\tmp\fullRelease
mkdir build\tmp\fullRelease
echo Copying server ...
copy %userprofile%\.gradle\caches\minecraft\net\minecraft\minecraft_server\1.12.2\minecraft_server-1.12.2.jar build\tmp\fullRelease > nul
mkdir build\tmp\fullRelease\patches
echo Extracting patches ...
7za x build\distributions\Carpetmod_dev.zip -bd -obuild\tmp\fullRelease\patches > nul
echo Patch work ...
7za a build\tmp\fullRelease\minecraft_server-1.12.2.jar .\build\tmp\fullRelease\patches\* > nul
echo Cleanup ...
rd /s /q build\tmp\fullRelease\patches
move /y build\tmp\fullRelease\minecraft_server-1.12.2.jar %appdata%\.minecraft\saves\minecraft_server.1.12.2_carpet_test.jar > nul
pushd %appdata%\.minecraft\saves
echo Starting server ...
java -jar minecraft_server.1.12.2_carpet_test.jar --nogui
popd
