name: Build on Pull Request

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          yes | ./gradlew setupCarpetmod
          yes | ./gradlew createRelease
      - uses: actions/upload-artifact@v2
        with:
          name: "Compiled carpetmod for Pull Request #${{github.event.number}}"
          path: build/distributions/Carpetmod_dev.zip