name: Build on Pull Request

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew
      - name: Build gradle
        run: |
          yes | ./gradlew setupCarpetmod
          yes | ./gradlew createRelease

      - uses: actions/upload-artifact@v2
        with:
          name: carpet-dev-${{ github.event.number }}
          path: build/distributions/Carpetmod_dev.zip
